import type { ApprovedGuardian } from '../../lib/types.js';
import { LoginType, LoginTypeLabel, OperationType } from '../../lib/types.js';

export interface NormalizedApprovedGuardian extends ApprovedGuardian {
  identifier?: string;
  identifierHash: string;
  type: LoginType;
  verifierId: string;
  verificationDoc: string;
  signature: string;
}

export function parseLoginType(value: string | number, field: string): LoginType {
  if (typeof value === 'number') {
    if (LoginTypeLabel[value as LoginType]) return value as LoginType;
    throw new Error(`${field} must be a valid login type number`);
  }

  const text = String(value || '').trim();
  if (!text) throw new Error(`${field} is required`);

  const numeric = Number(text);
  if (!Number.isNaN(numeric) && LoginTypeLabel[numeric as LoginType]) {
    return numeric as LoginType;
  }

  const byLabel = Object.entries(LoginTypeLabel).find(
    ([, label]) => label.toLowerCase() === text.toLowerCase(),
  );
  if (byLabel) return Number(byLabel[0]) as LoginType;

  throw new Error(`${field} must be a valid login type (e.g. 0 or "Email")`);
}

export function extractOperationTypeFromVerificationDoc(verificationDoc: string): number | null {
  const parts = verificationDoc.split(',');
  if (parts.length < 6) return null;

  const operationType = Number(parts[5]);
  return Number.isFinite(operationType) ? operationType : null;
}

export function toBytes(value: string | Buffer | Uint8Array): Buffer | Uint8Array {
  if (Buffer.isBuffer(value) || value instanceof Uint8Array) return value;
  if (typeof value === 'string') return Buffer.from(value, 'hex');
  return value;
}

export function normalizeTransferGuardiansApproved(
  guardians?: ApprovedGuardian[],
  label = 'guardiansApproved',
): NormalizedApprovedGuardian[] | undefined {
  if (!Array.isArray(guardians) || guardians.length === 0) return undefined;

  return guardians.map((guardian, index) => {
    if (!guardian || typeof guardian !== 'object') {
      throw new Error(`${label}[${index}] must be an object`);
    }

    const verifierId = guardian.verifierId?.trim();
    if (!verifierId) {
      throw new Error(`${label}[${index}].verifierId is required`);
    }

    const verificationDoc = guardian.verificationDoc?.trim();
    if (!verificationDoc) {
      throw new Error(`${label}[${index}].verificationDoc is required`);
    }

    const signature = guardian.signature?.trim();
    if (!signature) {
      throw new Error(`${label}[${index}].signature is required`);
    }

    const type = parseLoginType(guardian.type, `${label}[${index}].type`);
    const operationType = extractOperationTypeFromVerificationDoc(verificationDoc);
    if (operationType !== OperationType.GuardianApproveTransfer) {
      throw new Error(
        `${label}[${index}].verificationDoc must be generated by verify-code with operation "transferApprove" (operationType=10), got ${operationType ?? 'unknown'}`,
      );
    }

    const identifier = guardian.identifier?.trim();
    const identifierHash = guardian.identifierHash?.trim() || extractIdentifierHashFromVerificationDoc(verificationDoc);
    if (!identifier && !identifierHash) {
      throw new Error(`${label}[${index}].identifier or identifierHash is required`);
    }
    if (!identifierHash) {
      throw new Error(`${label}[${index}].identifierHash is required or derivable from verificationDoc`);
    }

    return {
      ...guardian,
      identifier,
      identifierHash,
      verifierId,
      verificationDoc,
      signature,
      type,
    };
  });
}

export function toContractApprovedGuardians(guardians?: NormalizedApprovedGuardian[]) {
  if (!guardians?.length) return undefined;

  return guardians.map((guardian) => ({
    identifierHash: guardian.identifierHash,
    type: guardian.type,
    verificationInfo: {
      id: guardian.verifierId,
      signature: toBytes(guardian.signature),
      verificationDoc: guardian.verificationDoc,
    },
  }));
}

function extractIdentifierHashFromVerificationDoc(verificationDoc: string): string {
  const parts = verificationDoc.split(',');
  return parts[1]?.trim() || '';
}
