#!/usr/bin/env python3
"""
Skill: Gemini Vision Analyzer
Author: Moxan <namemoxan@gmail.com>
Description: Analyzes images using Google Gemini 2.0 Flash with proxy support, retry logic, and mock mode.
Dependencies: google-generativeai, pydantic, Pillow
Track: AI-Enhanced Productivity
Version: 1.0.0
"""

import base64
import json
import logging
import os
import random
import time
from typing import Optional, List

try:
    import google.generativeai as genai
    from spoon_ai.tools.base import BaseTool
    from pydantic import Field
except ImportError:
    # Fallback for environments without spoon_ai
    from pydantic import BaseModel, Field
    class BaseTool(BaseModel):
        """Fallback BaseTool for portability."""
        name: str = ""
        description: str = ""
        parameters: dict = {}
        async def execute(self, **kwargs): pass

logger = logging.getLogger(__name__)


class GeminiVisionTool(BaseTool):
    """
    Analyze images using Google Gemini Vision API.

    Features:
    - Proxy support via HTTPS_PROXY/HTTP_PROXY
    - Retry logic for 429/Quota errors
    - Mock mode via MOCK_VISION env var
    - JSON structured response
    """

    name: str = "gemini_vision_analyze"
    description: str = "Analyze an image using Google Gemini Vision API. Returns structured analysis with label, description, and confidence score."
    parameters: dict = Field(default={
        "type": "object",
        "properties": {
            "image_base64": {
                "type": "string",
                "description": "Base64 encoded image data"
            },
            "prompt": {
                "type": "string",
                "description": "Analysis prompt instruction (e.g., 'Describe this image', 'Is there a cat?')"
            },
            "valid_labels": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Optional list of valid labels to validate against"
            }
        },
        "required": ["image_base64", "prompt"]
    })

    async def execute(
        self,
        image_base64: str,
        prompt: str,
        valid_labels: Optional[List[str]] = None,
        **kwargs
    ) -> dict:
        """
        Execute image analysis.

        Args:
            image_base64: Base64 encoded image data
            prompt: Analysis prompt instruction
            valid_labels: Optional list of valid labels to validate against

        Returns:
            dict with analysis results including is_valid, label, description, confidence
        """
        model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

        # Mock mode for testing
        if os.getenv("MOCK_VISION", "false").lower() == "true":
            selected_label = random.choice(valid_labels) if valid_labels else "mock_object"
            logger.info(f"[MOCK MODE] Returning mock analysis: {selected_label}")
            return {
                "is_valid": True,
                "label": selected_label,
                "description": "This is a mock description generated in test mode.",
                "confidence": 0.95,
                "details": {
                    "features": ["mock_feature_1", "mock_feature_2"],
                    "notes": "Generated by MOCK_VISION mode"
                }
            }

        try:
            # Configure proxy for Gemini API access
            proxy = os.getenv("HTTPS_PROXY") or os.getenv("HTTP_PROXY")
            if proxy:
                os.environ["HTTP_PROXY"] = proxy
                os.environ["HTTPS_PROXY"] = proxy
                os.environ["GRPC_PROXY"] = proxy
                logger.info(f"Using proxy for Gemini API: {proxy}")

            # Configure Gemini API key
            api_key = os.getenv("GEMINI_API_KEY")
            if not api_key:
                logger.warning("GEMINI_API_KEY not set")
                return {"is_valid": False, "description": "API Key missing", "confidence": 0.0}

            # WORKAROUND: Disable SSL verification for Proxy envs if needed
            import ssl
            import urllib3
            urllib3.disable_warnings()
            try:
                _create_unverified_https_context = ssl._create_unverified_context
            except AttributeError:
                pass
            else:
                ssl._create_default_https_context = _create_unverified_https_context

            genai.configure(api_key=api_key, transport="rest")

            # Configure Gemini model
            model = genai.GenerativeModel(model_name)
            logger.info(f"Using Gemini model: {model_name}")

            # Append JSON formatting instruction to prompt
            json_instruction = """
Please respond in strict JSON format with the following structure:
{
    "is_valid": true/false,
    "label": "classification_label",
    "description": "detailed description",
    "confidence": 0.0-1.0,
    "details": {
        "features": [],
        "issues": [],
        "recommendations": []
    }
}
"""
            full_prompt = f"{prompt}\n\n{json_instruction}"

            # Call API with retry
            max_retries = 3
            retry_delay = 5
            response = None

            for attempt in range(max_retries):
                try:
                    response = model.generate_content([
                        full_prompt,
                        {"mime_type": "image/jpeg", "data": image_base64}
                    ])
                    break
                except Exception as e:
                    error_str = str(e).lower()
                    if "429" in error_str or "resource exhausted" in error_str:
                        if attempt < max_retries - 1:
                            wait_time = retry_delay * (attempt + 1)
                            logger.warning(f"Rate limited, waiting {wait_time}s...")
                            time.sleep(wait_time)
                            continue
                    raise

            if response is None:
                return {"is_valid": False, "description": "No response from API", "confidence": 0.0}

            # Parse response
            response_text = response.text
            if "```json" in response_text:
                response_text = response_text.split("```json")[1].split("```")[0]
            elif "```" in response_text:
                response_text = response_text.split("```")[1].split("```")[0]

            result = json.loads(response_text.strip())

            # Optional label validation
            if valid_labels and result.get("label") and result["label"] not in valid_labels:
                result["label"] = None
                result["is_valid"] = False
                result["description"] = "Unrecognized object type"

            return result

        except Exception as e:
            logger.error(f"Vision analysis error: {e}")
            return {
                "is_valid": False,
                "description": f"Analysis error: {str(e)}",
                "confidence": 0.0
            }


# Convenience function for direct usage
async def vision_analyze(image: bytes, prompt: str, valid_labels: Optional[List[str]] = None) -> dict:
    """
    Convenience wrapper for GeminiVisionTool.

    Args:
        image: Raw image bytes
        prompt: Analysis prompt instruction
        valid_labels: Optional list of valid labels

    Returns:
        dict with analysis results
    """
    tool = GeminiVisionTool()
    image_base64 = base64.b64encode(image).decode('utf-8')
    return await tool.execute(image_base64=image_base64, prompt=prompt, valid_labels=valid_labels)
