#!/usr/bin/env python3
"""senpi-strategy-discover engine — Data Layer + concrete Filter (hidden, deterministic).

The agent (LLM) runs this via the OpenClaw `exec` tool with discrete flags; it reads the JSON on
stdout, RANKS the returned set itself (on risk / belief / worldview / thesis), and narrates 2-3 cards.

  python3 discover.py --assets btc_eth --direction long_only

Contract:
- The SCRIPT only does CONCRETE set logic: it hard-rejects on the few unambiguous, explicitly-stated
  constraints (cross-domain asset, named-asset unavailable, strict-opposite direction, explicit
  exclusions). It computes the complete eligible set, reports its count, and bounds default output.
- Survivors are neutral-ordered (asset-match desc, then name); optional theme scoring runs over the
  complete eligible set, then each variant family folds into one card, then the output cap — so a
  later candidate can still surface and near-identical siblings can't fill the shortlist.
- Each record carries a compact soft-rank surface (risk_level, belief_plain, THESIS, tags, horizon,
  scope, direction, asset_classes, tier) + caveats + market_facts. The LLM does ALL soft/semantic
  ranking — nothing it matches on requires a maintained glossary.
- Fails open: unknown concrete values drop to "unstated" (widen, never dead-end); always valid JSON;
  exit 0 for handled cases.
"""
# Copyright 2026 Senpi (https://senpi.ai) — Apache-2.0
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
# The catalog is generated by senpi-trading-runtime/scripts/gen_catalog.py, which writes BOTH the repo
# copy (source of truth, next to the packages) AND the skill-local copy below (so the catalog travels
# with the skill when it's installed standalone — where ../../strategies/ does NOT exist). Resolution
# order: --catalog fixture (tests) → skill-local → repo checkout → one remote fetch of catalog.json.
SKILL_CATALOG = os.path.join(HERE, os.pardir, "catalog.json")             # bundled with the discover skill
REPO_CATALOG = os.path.join(REPO_ROOT, "strategies", "catalog.json")      # dev checkout / source of truth
_CATALOG_REPO = os.environ.get("SENPI_SKILLS_REPO", "Senpi-ai/senpi-skills")
_CATALOG_REF = os.environ.get("SENPI_SKILLS_REF", "main")
DEFAULT_LIMIT = 8
OUTPUT_BUDGET = 12_000
TEXT_FIELD_LIMIT = 120
TAG_LIMIT = 8
MARKET_FACT_LIMIT = 2


def default_catalog():
    """First catalog that exists locally; else the skill-local path (load_catalog fetches + caches there)."""
    for p in (SKILL_CATALOG, REPO_CATALOG):
        if os.path.isfile(p):
            return p
    return SKILL_CATALOG

# ---------------------------------------------------------------- vocabulary (concrete filters only)
# A synonym map is kept ONLY because the SCRIPT acts on the field. risk/belief/horizon/scope/goal are
# the LLM's job now (it ranks the returned set on them) — no flags, no maps for those.
CLASS_TAGS = {"btc_eth", "major_alts", "universe_crypto", "xyz_equities", "commodities", "indices", "pre_ipo"}
CRYPTO_CLASSES = {"btc_eth", "major_alts", "universe_crypto"}
XYZ_CLASSES = {"xyz_equities", "commodities", "indices", "pre_ipo"}

ASSET_SYN = {**{t: t for t in CLASS_TAGS},
             "btc": "btc_eth", "eth": "btc_eth", "bitcoin": "btc_eth", "ethereum": "btc_eth", "btceth": "btc_eth",
             "alts": "major_alts", "altcoins": "major_alts", "alt": "major_alts", "majors": "major_alts",
             "everything": "universe_crypto", "scan": "universe_crypto", "all": "universe_crypto", "universe": "universe_crypto",
             "stocks": "xyz_equities", "stock": "xyz_equities", "equities": "xyz_equities", "equity": "xyz_equities", "tech": "xyz_equities",
             "oil": "commodities", "gold": "commodities", "silver": "commodities", "metals": "commodities", "commodity": "commodities",
             "xauusd": "commodities", "xau": "commodities", "xagusd": "commodities",
             "index": "indices", "sp500": "indices", "nasdaq": "indices",
             "pre-ipo": "pre_ipo", "preipo": "pre_ipo", "ipo": "pre_ipo", "spacex": "pre_ipo"}
DIRECTION_SYN = {"long_only": "long_only", "long-only": "long_only", "longonly": "long_only", "long": "long_only",
                 "no-short": "long_only", "no-shorting": "long_only", "longs": "long_only",
                 "short_only": "short_only", "short-only": "short_only", "shorts": "short_only", "short": "short_only",
                 "any": "any", "both": "any"}
# exclude token -> (dimension, canonical value)
EXCLUDE_SYN = {
    "copy": ("archetype", "copy_trading"), "copy_trading": ("archetype", "copy_trading"),
    "copy-trading": ("archetype", "copy_trading"), "mirror": ("archetype", "copy_trading"),
    "stocks": ("asset_class", "xyz_equities"), "equities": ("asset_class", "xyz_equities"),
    "crypto": ("asset_class", "__crypto__"), "commodities": ("asset_class", "commodities"),
    "oil": ("asset_class", "commodities"), "pre-ipo": ("asset_class", "pre_ipo"), "pre_ipo": ("asset_class", "pre_ipo"),
    "dca": ("sub_style", "dca"), "shorting": ("direction", "no_short"), "shorts": ("direction", "no_short"),
}


# ---------------------------------------------------------------- normalizer (concrete inputs only)
def _canon(value, synmap, warnings, field):
    if value is None:
        return None
    key = str(value).strip().lower()
    for cand in (key, key.replace(" ", "-"), key.replace(" ", "_"), key.replace(" ", "")):
        if cand in synmap:
            canon = synmap[cand]
            if canon != key:
                warnings.append(f"normalized {field} '{value}' -> '{canon}'")
            return canon
    warnings.append(f"dropped {field}='{value}' (unrecognized) -> unstated")
    return None


def _parse_budget(value, warnings):
    if value is None:
        return None
    s = str(value).lower().replace(",", "").replace("$", "").replace("~", "")
    s = s.replace("around", "").replace("about", "").strip()
    nums = []
    for tok in re.finditer(r"(\d+(?:\.\d+)?)(\s*[kK])?", s):
        n = float(tok.group(1))
        if tok.group(2):
            n *= 1000
        nums.append(n)
    if not nums:
        warnings.append(f"dropped budget='{value}' (no number) -> unstated")
        return None
    if len(nums) >= 2 and "-" in s:   # a range like "500-2000" -> midpoint
        return (nums[0] + nums[1]) / 2.0
    return nums[0]


def _norm_assets(raw, warnings):
    """Split csv; each token -> ('class', tag) or ('named', TICKER)."""
    out = []
    if not raw:
        return out
    for tok in str(raw).split(","):
        t = tok.strip()
        if not t:
            continue
        low = t.lower()
        if low in ASSET_SYN:
            cls = ASSET_SYN[low]
            if ("class", cls) not in out:
                out.append(("class", cls))
        else:
            named = t.upper()
            if ("named", named) not in out:
                out.append(("named", named))
    return out


def _norm_exclude(raw, warnings):
    out = []
    if not raw:
        return out
    for tok in str(raw).split(","):
        t = tok.strip().lower()
        if not t:
            continue
        if t in EXCLUDE_SYN:
            pair = EXCLUDE_SYN[t]
            if pair not in out:
                out.append(pair)
        else:
            warnings.append(f"dropped exclude='{tok.strip()}' (unrecognized)")
    return out


def normalize_intent(args):
    w = []
    intent = {
        "direction": _canon(getattr(args, "direction", None), DIRECTION_SYN, w, "direction"),
        "budget": _parse_budget(getattr(args, "budget", None), w),
        "assets": _norm_assets(getattr(args, "assets", None), w),
        "exclude": _norm_exclude(getattr(args, "exclude", None), w),
    }
    if intent["direction"] == "any":
        intent["direction"] = None
    intent["_warnings"] = w
    return intent


# ---------------------------------------------------------------- helpers
def domain_of(classes):
    d = set()
    if any(c in CRYPTO_CLASSES for c in classes):
        d.add("crypto")
    if any(c in XYZ_CLASSES for c in classes):
        d.add("xyz")
    return d


def asset_matches(named, assets):
    nu = named.upper().replace("XYZ:", "")
    for a in (assets or []):
        au = str(a).upper()
        if au == nu or au == "XYZ:" + nu or au.split(":")[-1] == nu:
            return True
    return False


def _configurable(r):
    """A user-parameterized single-asset template (e.g. gecko) trades ANY liquid coin the
    user sets at deploy, so a named-asset intent must NOT filter it out — it's precisely the
    answer when no fixed-asset template covers the coin. Flagged by a catalog tag."""
    tags = [str(t).lower() for t in (r.get("tags") or [])]
    return "configurable" in tags or "any-asset" in tags


def infer_class_for_named(named):
    n = named.upper().replace("XYZ:", "")
    if named.upper().startswith("XYZ:"):
        return None  # xyz domain but sub-class unknown; broaden = no class constraint
    if n in ("BTC", "ETH"):
        return "btc_eth"
    return "major_alts"


# ---------------------------------------------------------------- matcher (pure: filter + return all)
def _hard_reject(r, intent):
    """The ONLY narrowing — reject on an explicitly-stated, unambiguous constraint. Nothing soft."""
    user_classes = [v for k, v in intent["assets"] if k == "class"]
    if user_classes:
        ud, sd = domain_of(user_classes), domain_of(r.get("asset_classes") or [])
        if ud and sd and ud.isdisjoint(sd):
            return True
    named = [v for k, v in intent["assets"] if k == "named"]
    if named and not _configurable(r) and not any(asset_matches(n, r.get("assets")) for n in named):
        if not intent.get("_broadened_classes"):
            return True
        if not (set(intent["_broadened_classes"]) & set(r.get("asset_classes") or [])):
            return True
    d = intent["direction"]
    if d == "long_only" and r.get("direction") == "short_only":
        return True
    if d == "short_only" and r.get("direction") == "long_only":
        return True
    for dim, val in intent["exclude"]:
        if dim == "archetype" and r.get("archetype") == val:
            return True
        if dim == "asset_class":
            acs = r.get("asset_classes") or []
            if val == "__crypto__" and (set(acs) & CRYPTO_CLASSES):
                return True
            if val in acs:
                return True
        if dim == "sub_style" and r.get("sub_style") == val:
            return True
        if dim == "direction" and val == "no_short" and r.get("direction") in ("short_only", "long_short"):
            return True
    return False


def _asset_match(r, intent):
    """Neutral ORDERING key (not a filter): how many stated asset constraints this record satisfies."""
    n = 0
    user_classes = [v for k, v in intent["assets"] if k == "class"]
    named = [v for k, v in intent["assets"] if k == "named"]
    acs = set(r.get("asset_classes") or [])
    if user_classes and (set(user_classes) & acs):
        n += 1
    if named and any(asset_matches(x, r.get("assets")) for x in named):
        n += 1
    return n


def _caveats(r, intent):
    """Fixed-string honesty caveats — concrete only (no soft scoring). Surfaced verbatim by the LLM."""
    cav = []
    user_classes = [v for k, v in intent["assets"] if k == "class"]
    named = [v for k, v in intent["assets"] if k == "named"]
    acs = set(r.get("asset_classes") or [])
    if named and _configurable(r) and not any(asset_matches(x, r.get("assets")) for x in named):
        cav.append(f"Configurable — set it to trade {named[0]} (or any liquid coin) at deploy.")
    if "btc_eth" in user_classes and "btc_eth" not in acs and (acs & CRYPTO_CLASSES):
        cav.append("Trades alts beyond just BTC/ETH.")
    if intent["direction"] == "long_only" and r.get("direction") == "long_short":
        cav.append("Can also take short positions.")
    if (r.get("instance_count") or 1) > 1 and (user_classes or [v for k, v in intent["assets"] if k == "named"]):
        split = "/".join(str(s) for s in (r.get("funding_split") or []))
        cav.append(f"Splits across {r['instance_count']} wallets ({split}); your assets may sit mainly in one leg.")
    if intent["budget"] is not None and intent["budget"] < (r.get("min_budget") or 0):
        wc = r.get("wallet_count") or (r.get("instance_count") or 1)
        wtxt = f" ({wc} wallets)" if wc and wc > 1 else ""
        cav.append(f"Minimum ${int(r['min_budget'])}{wtxt} for the full design; you mentioned "
                   f"${int(intent['budget'])} — it still deploys but runs degraded (fewer slots than designed).")
    return cav


def _min_budget(r):
    """The COMPUTED minimum total budget to run this strategy as designed (min_budget.py, baked into
    catalog.json by gen_catalog): the smallest budget where every wallet funds and its smallest slot
    clears the $12 bumped notional. NOT a recommendation — users size their own budget above the min."""
    return int(r.get("min_budget") or 10)


def _intent_echo(intent):
    echo = {}
    if intent.get("direction"):
        echo["direction"] = intent["direction"]
    if intent.get("budget") is not None:
        v = intent["budget"]
        echo["budget"] = int(v) if isinstance(v, float) and v.is_integer() else v
    if intent["assets"]:
        echo["assets"] = [v for _, v in intent["assets"]]
    if intent["exclude"]:
        echo["exclude"] = [f"{d}:{v}" for d, v in intent["exclude"]]
    return echo


def _active_constraints(intent):
    c = []
    if [v for k, v in intent["assets"] if k == "class"]:
        c.append("asset-class")
    if [v for k, v in intent["assets"] if k == "named"]:
        c.append("named-asset")
    if intent["direction"] in ("long_only", "short_only"):
        c.append(f"direction:{intent['direction']}")
    for dim, val in intent["exclude"]:
        c.append(f"exclude:{dim}:{val}")
    return c


def _short_text(value):
    value = str(value or "")
    return value if len(value) <= TEXT_FIELD_LIMIT else value[:TEXT_FIELD_LIMIT - 1].rstrip() + "…"


def _candidate(r, intent):
    """A flat, labels-pre-inlined record — everything the LLM needs to rank + narrate. Full text here so
    theme scoring sees it; `limit_result` compacts only the returned candidates (`_compact`)."""
    cand = {
        # identity + handoff
        "id": r.get("id"), "version": r.get("version"), "name": r.get("name"),
        "emoji": r.get("emoji"), "tagline": r.get("tagline"),
        # The template this one VARIES, when it is a variant (fold_variants groups families on it).
        # On a returned card it means the family root was filtered out and this member stands in.
        "varies": r.get("varies"),
        # soft-rank surface (the script never reads these — the LLM ranks on them)
        "risk_level": r.get("risk_level"), "archetype_label": r.get("archetype_label"),
        "belief_plain": r.get("belief_plain"), "thesis": r.get("thesis"), "tags": r.get("tags") or [],
        "time_horizon": r.get("time_horizon"), "asset_scope": r.get("asset_scope"),
        "direction": r.get("direction"), "asset_classes": r.get("asset_classes") or [],
        "assets": r.get("assets") or [], "tier": r.get("tier"),
        # narration — min_budget is the COMPUTED minimum where the design functions (not a recommendation;
        # users size above it). wallet_count lets the card render "Minimum $200 (3 wallets)".
        "min_budget": _min_budget(r),
        "wallet_count": r.get("wallet_count") or (r.get("instance_count") or 1),
        "min_budget_binding_wallet": r.get("min_budget_binding_wallet"),
        "caveats": _caveats(r, intent),
        "market_facts": [],
    }
    if r.get("tag_labels"):
        cand["tag_labels"] = r.get("tag_labels")
    if (r.get("instance_count") or 1) > 1:
        cand["funding_split"] = r.get("funding_split")
    return cand


def _compact(cand):
    """Output projection: trim the long soft-rank text so the shortlist fits the result budget."""
    for field in ("tagline", "belief_plain", "thesis"):
        cand[field] = _short_text(cand.get(field))
    for field in ("tags", "tag_labels"):
        if field in cand:
            cand[field] = cand[field][:TAG_LIMIT]
    return cand


def match(intent, records):
    """Filter on the concrete constraints, return ALL survivors neutral-ordered. No score, no top-N."""
    intent.setdefault("_broadened_classes", [])
    survivors = [r for r in records if not _hard_reject(r, intent)]
    widened = []

    # The ONLY graceful degrade: a named asset nobody trades broadens to its class (never silent on
    # cross-domain / direction / exclusions — those stay rejected; the conversation may offer widening).
    named = [v for k, v in intent["assets"] if k == "named"]
    if not survivors and named:
        broadened = [c for c in (infer_class_for_named(n) for n in named) if c]
        i2 = dict(intent)
        i2["assets"] = [(k, v) for k, v in intent["assets"] if k != "named"]
        i2["_broadened_classes"] = broadened
        survivors = [r for r in records if not _hard_reject(r, i2)]
        if survivors:
            widened.append("named_asset")
            intent = i2

    build_custom = {"label": "Build a custom strategy", "route": "senpi-strategy-author"}
    survivors.sort(key=lambda r: (-_asset_match(r, intent), r.get("name") or r.get("id") or ""))
    candidates = [_candidate(r, intent) for r in survivors]
    meta = {"eligible_count": len(candidates), "returned_n": len(candidates),
            "intent_echo": _intent_echo(intent), "warnings": intent.get("_warnings", [])}
    if widened:
        meta["widened"] = widened
    if not candidates:
        meta["unmet"] = _active_constraints(intent)
    return {"candidates": candidates, "build_custom": build_custom, "meta": meta}


# ---------------------------------------------------------------- theme search (SOFT surface, no filter)
# A worldview/market-structure keyword ("k-shape", "risk-off", "market-neutral") rarely appears verbatim
# in every matching thesis — so a naked substring search misses obvious fits (e.g. Cub self-describes as a
# "Two-Speed-Market Long/Short" but never says the phrase "k-shape"). The DIVISION OF LABOR:
#   * the LLM (the analyst, per SKILL.md) supplies the semantic expansion — it natively knows
#     "k-shape" ≈ "two-speed" ≈ "long/short" ≈ "dispersion" and passes those terms in --theme;
#   * this engine does DETERMINISTIC weighted keyword-overlap over the real catalog fields on whatever
#     terms it is handed, floats the matches to the top, and echoes a ranked shortlist.
# It is SOFT — never drops a candidate; only surfaces + orders. There is NO repo-maintained synonym map
# here (that would duplicate glossary.yaml and rot); the vocabulary lives with the LLM. This still fixes
# "the agent eyeballed 78 theses and missed the K-shape strategies" — the agent stops eyeballing because
# the engine returns a ranked shortlist from the theses' own words.
# fields scored, with weight — a hit in a tag/tagline is a stronger signal than one buried in the thesis.
_THEME_FIELDS = (("tags", 3), ("tag_labels", 3), ("tagline", 2), ("name", 2),
                 ("archetype_label", 2), ("thesis", 1), ("belief_plain", 1))
# Categorical labels for the two asks SKILL.md routes into --theme. They hit on a WHOLE term equal to
# the rendered label, never a substring: the horizon label "position" (days-to-weeks holds) is also the
# everyday word in "one concentrated position", so it is rendered "position-horizon" — a bare
# "position" is not a horizon ask. Weights: risk_level 6 (two tag hits) so a stated risk appetite
# outranks incidental text — on "conservative defensive low-risk hedged" over btc_eth the best
# wrong-risk record scores 5 from text alone; time_horizon 3 (one tag hit) because horizon words are
# nearly absent from catalog text — an "intraday-horizon" ask returned 3/8 intraday at 1, 8/8 at 3.
_THEME_LABELS = (("risk_level", "{}", 6), ("time_horizon", "{}-horizon", 3))


def _norm_text(s):
    """Lowercase + collapse separators (/ _ - whitespace → single space) so 'long/short', 'long-short'
    and 'long short' all compare equal."""
    return re.sub(r"[\s/_-]+", " ", str(s or "").lower()).strip()


def _expand_theme(query):
    """Free-text theme query → normalized term set. Deterministic only: split on whitespace/comma into
    individual terms, plus the whole phrase (hyphenated). NO synonym lookup — the LLM already expanded
    the worldview into its structural synonyms before calling (see SKILL.md `--theme`)."""
    q = str(query or "").lower().strip()
    keys = [t for t in re.split(r"[,\s]+", q) if t]
    keys.append(re.sub(r"\s+", "-", q))          # whole phrase, hyphenated: "long short" -> "long-short"
    return sorted({_norm_text(t) for t in keys if t and _norm_text(t)})


def _theme_score(cand, terms):
    """Weighted count of theme-term hits across a candidate's searchable surface → (score, sorted hits)."""
    score, hits = 0, set()
    for field, weight in _THEME_FIELDS:
        val = cand.get(field)
        text = _norm_text(" ".join(str(x) for x in val)) if isinstance(val, list) else _norm_text(val)
        if not text:
            continue
        for t in terms:
            if t and t in text:
                score += weight
                hits.add(t)
    for field, label, weight in _THEME_LABELS:
        t = _norm_text(label.format(cand[field])) if cand.get(field) else ""
        if t and t in terms:
            score += weight
            hits.add(t)
    return score, sorted(hits)


def _theme_matches(cands):
    return [{"id": c["id"], "name": c.get("name"), "theme_score": c["theme_score"],
             "theme_hits": c.get("theme_hits", [])}
            for c in cands if c.get("theme_score", 0) > 0]


def apply_theme(result, query):
    """SOFT theme surface over the complete filtered set: score each candidate on keyword overlap,
    STABLE-sort matches to the top (ties keep the prior asset/name order), and echo the ranked matches +
    the expanded terms in meta. Drops nothing itself — the output cap (limit_result) runs after it."""
    terms = _expand_theme(query)
    for cand in result.get("candidates", []):
        score, hits = _theme_score(cand, terms)
        cand["theme_score"] = score
        if hits:
            cand["theme_hits"] = hits
    result["candidates"].sort(key=lambda c: -c.get("theme_score", 0))
    result.setdefault("meta", {})["theme"] = query
    result["meta"]["theme_expanded"] = terms
    result["meta"]["theme_matches"] = _theme_matches(result["candidates"])
    return result


def _family_chain(cid, varies):
    """[cid, parent, grandparent, …] following the catalog `varies` field up to the family root."""
    chain = [cid]
    while varies.get(chain[-1]) and varies[chain[-1]] not in chain:
        chain.append(varies[chain[-1]])
    return chain


def fold_variants(result, records):
    """One card per variant family, before the output cap — so near-identical siblings can't eat the
    shortlist (references/variant-families.md: offer variants only through their parent).

    The family root is found by following `varies` up the FULL catalog (a chain can pass through a
    filtered-out record). The card is the eligible member closest to the root (best-ranked on a tie), so
    an eligible variant still surfaces when its root was filtered out. It lists the other eligible
    members in `variants`, carries the family's best theme_score (a variant's match lifts its root) and
    the union of their theme_hits, and sits where the family's best-ranked member sat. eligible_count
    still counts every eligible record; meta.families_count counts the cards the set folds into."""
    varies = {r.get("id"): (r.get("varies") or "").strip() for r in records}
    families = {}
    for rank, cand in enumerate(result.get("candidates", [])):
        chain = _family_chain(cand["id"], varies)
        families.setdefault(chain[-1], []).append((len(chain), rank, cand))
    cards = []
    for members in families.values():
        rep = min(members, key=lambda m: m[:2])[2]
        others = [c for _, _, c in members if c is not rep]
        if others:
            rep["variants"] = [c["id"] for c in others]
            if "theme_score" in rep:
                rep["theme_score"] = max(c["theme_score"] for _, _, c in members)
                hits = sorted({h for _, _, c in members for h in c.get("theme_hits", [])})
                if hits:
                    rep["theme_hits"] = hits
        cards.append((-rep.get("theme_score", 0), members[0][1], rep))
    result["candidates"] = [c for *_, c in sorted(cards, key=lambda k: k[:2])]
    meta = result.setdefault("meta", {})
    meta["families_count"] = len(result["candidates"])
    if "theme_matches" in meta:
        meta["theme_matches"] = _theme_matches(result["candidates"])
    return result


def limit_result(result, limit):
    """Apply the output cap after every ranking pass while preserving full-set counts, then compact only
    the returned candidates — ranking already ran on full text."""
    if limit is not None:
        limit = max(0, limit)
        result["candidates"] = result.get("candidates", [])[:limit]
        if "theme_matches" in result.get("meta", {}):
            result["meta"]["theme_matches"] = result["meta"]["theme_matches"][:limit]
    for cand in result.get("candidates", []):
        _compact(cand)
    result.setdefault("meta", {})["returned_n"] = len(result.get("candidates", []))
    return result


TRIM_WARNING = "output trimmed to fit the result budget: lowest-ranked market_facts, then candidates, dropped"


def fit_budget(result, budget):
    """Degrade an over-budget result instead of failing closed: drop market_facts from the lowest-ranked
    candidates first, then candidates from the bottom — never below one (a short answer beats an empty
    one). eligible_count is untouched; returned_n carries the count that survived."""
    def size():
        return len(json.dumps(result, ensure_ascii=False))

    if size() <= budget:
        return result
    meta = result.setdefault("meta", {})
    cands = result.setdefault("candidates", [])
    meta.setdefault("warnings", []).append(TRIM_WARNING)
    for cand in reversed(cands):
        if size() <= budget:
            return result
        cand["market_facts"] = []
    while len(cands) > 1 and size() > budget:
        cands.pop()
        meta["returned_n"] = len(cands)
        if "theme_matches" in meta:
            kept = {c.get("id") for c in cands}
            meta["theme_matches"] = [m for m in meta["theme_matches"] if m.get("id") in kept]
    return result


# ---------------------------------------------------------------- data layer (guarded I/O)
def _fetch_catalog(dest):
    """Fetch the single generated catalog.json from the remote (one request, not per-strategy) and cache
    it. Returns a readable path — `dest` if writable, else a temp file. Used only when no local copy
    exists (e.g. a standalone install that didn't bundle it)."""
    import http.client
    conn = http.client.HTTPSConnection("raw.githubusercontent.com", timeout=20)
    try:
        conn.request("GET", f"/{_CATALOG_REPO}/{_CATALOG_REF}/strategies/catalog.json",
                     headers={"User-Agent": "senpi-strategy-discover", "Accept": "*/*"})
        resp = conn.getresponse()
        body = resp.read()
        if resp.status != 200:
            raise RuntimeError(f"catalog fetch HTTP {resp.status} from {_CATALOG_REPO}@{_CATALOG_REF}")
    finally:
        conn.close()
    for target in (dest, os.path.join(__import__("tempfile").gettempdir(), "senpi-catalog.json")):
        try:
            os.makedirs(os.path.dirname(target) or ".", exist_ok=True)
            with open(target, "wb") as f:
                f.write(body)
            return target
        except OSError:
            continue
    raise RuntimeError("could not write fetched catalog")


def load_catalog(path):
    if not os.path.isfile(path):
        path = _fetch_catalog(path)   # standalone install / missing local copy → fetch once + cache
    with open(path) as f:
        return (json.load(f).get("skills") or [])


def _get_client():
    # self-contained MCP client shipped in this skill — no senpi_runtime_helpers dependency
    if HERE not in sys.path:
        sys.path.insert(0, HERE)
    from mcp_client import MCPClient
    return MCPClient()


def _ok(resp):
    """Unwrap an MCP response; None if it failed (mcp_call returns success:False, not an exception)."""
    if isinstance(resp, dict):
        if resp.get("success") is False:
            return None
        return resp.get("data", resp)
    return resp


# ── what the user can actually deploy ──
#
# THE BALANCE-BUCKET TRAP. `account_get_portfolio` reports several totals and only one of them is
# money this user could put into a new strategy:
#
#   total_in_hyperliquid         free USDC in the FUNDING wallet's perps account
#   total_spot_usd_in_hyperliquid  ... its Spot balance
#   token_balances[]             ... EVM USDC, bridgeable
#   total_withdrawable           free margin sitting INSIDE strategy wallets — ALREADY COMMITTED
#   total_allocated_in_strategy  margin backing open strategy positions — ALREADY AT RISK
#   total_balance_usd            the sum of ALL of the above
#
# Only the first three are deployable. `senpi-portfolio/scripts/portfolio.py` calls this out as the
# balance-bucket trap and computes the same three pools; `senpi-strategy-ops/references/lifecycle.md`
# states the same waterfall for deploy preflight ("never `total_withdrawable`"). This function is the
# discover-side copy of that one rule.
#
# This read USED to be `total_balance_usd or total_in_hyperliquid`, which offers the user money that
# is already working. On the repo's own portfolio fixture that reported **$3,102.94** against a truly
# free balance of **$1.51** — the user had $3,101.43 live inside strategies. Observed on a real
# account 2026-10-02: the catalog offer quoted "~$6,470 free" when $21.06 was free and the rest was
# in seven running strategies.
#
# Returns 0.0 for a readable-but-empty balance. 0 is a FACT, not missing data: an `or` chain treats
# it as absent and reaches for the next field, which is how the committed-capital figure got in.
_DEPLOYABLE_STABLES = ("USDC", "USDC.E", "USDT")


def _accessible_usdc(portfolio):
    """Funding-wallet perps + Spot + EVM stables. Never strategy-held capital."""
    def _num(v):
        try:
            return float(v)
        except (TypeError, ValueError):
            return 0.0

    total = _num(portfolio.get("total_in_hyperliquid"))
    total += _num(portfolio.get("total_spot_usd_in_hyperliquid"))
    for tb in (portfolio.get("token_balances") or []):
        if not isinstance(tb, dict):
            continue
        sym = str(tb.get("tokenSymbol") or tb.get("symbol") or "").upper()
        if sym in _DEPLOYABLE_STABLES:
            total += _num(tb.get("balanceInUSD") or tb.get("usdValue") or tb.get("balanceUsd"))
    return round(total, 2)


# ── the user's saved wallets (Your wallets): holdings context only, never Senpi money ──
#
# A saved wallet is an address the user added in Your wallets and trades by hand — their claim, never
# checked. Senpi can read it and cannot place, change or cancel orders on it, so it is never a budget and
# never a deploy target. Its positions are read for one reason: a pick must not double an exposure the
# user already holds. Unknown is never empty — a failed read is "unavailable" with holdings None (never
# []), and a wallet whose state couldn't load is named in `saved_wallets_unread`, never read as flat.
SAVED_WALLETS_TIMEOUT_S = 25    # moxie answers within ~6.5 s; the MCP's own moxie timeout is 20 s — wait past it


def _short_addr(addr):
    return f"{addr[:6]}…{addr[-4:]}" if isinstance(addr, str) and len(addr) > 12 else addr


def fetch_saved_wallet_holdings(client):
    """`account_get_external_wallets` (no address: every saved wallet, each with its live `state`) →
    {saved_wallets_status, saved_wallet_holdings, saved_wallets_unread}. Never raises: a failed read
    degrades to status "unavailable" + `_saved_wallets_error`, and the rest of the context stands."""
    out = {"saved_wallets_status": "unavailable", "saved_wallet_holdings": None, "saved_wallets_unread": []}
    try:
        resp = _ok(client.mcp_call("account_get_external_wallets", timeout=SAVED_WALLETS_TIMEOUT_S))
        rows = resp.get("external_wallets") if isinstance(resp, dict) else None
        if not isinstance(rows, list):
            raise ValueError("no external_wallets list in the response")
    except Exception as e:  # noqa — unknown, never empty
        out["_saved_wallets_error"] = str(e)
        return out
    holdings = []
    for w in rows:
        if not isinstance(w, dict) or not isinstance(w.get("address"), str):
            continue
        name = w.get("label") or _short_addr(w["address"].strip().lower())
        st = w.get("state")
        if not isinstance(st, dict) or st.get("readError") or not isinstance(st.get("positions"), list):
            out["saved_wallets_unread"].append(name)
            continue
        for p in st["positions"]:
            if isinstance(p, dict) and p.get("coin"):
                holdings.append({"coin": p["coin"], "side": p.get("side"),
                                 "position_value_usd": p.get("positionValueUsd"),
                                 "wallet": name, "origin": "saved_wallet", "access": "read-only"})
    out["saved_wallets_status"] = "ok"
    out["saved_wallet_holdings"] = holdings
    return out


def fetch_active_strategy_count(client):
    """How many ACTIVE Senpi strategies the user runs (`strategy_list`), so an empty `holdings` (no open
    Senpi positions) is never read as "no strategies". None when the read failed — unknown, never 0."""
    try:
        resp = client.mcp_call("strategy_list", status=["ACTIVE"], timeout=20)
        data = _ok(resp)
        rows = data if isinstance(data, list) else (data.get("strategies") if isinstance(data, dict) else None)
        if not isinstance(rows, list):
            return None
        return sum(1 for r in rows if isinstance(r, dict) and str(r.get("status") or "ACTIVE").upper() == "ACTIVE")
    except Exception:  # noqa — unknown, never 0
        return None


def fetch_user_context(client, saved_wallets=False):
    """Budget (Senpi money only) + Senpi holdings; with `saved_wallets` (the `--context-only` read) also
    the positions on the wallets the user added — holdings context, never budget — and the active Senpi
    strategy count (`holdings: []` is "no open Senpi positions", never "no strategies")."""
    ctx = {"budget": None, "holdings": [], "favored_assets": [], "favored_direction": None}
    if saved_wallets:
        ctx["active_strategy_count"] = fetch_active_strategy_count(client)
        ctx.update(fetch_saved_wallet_holdings(client))
    try:
        data = _ok(client.mcp_call("account_get_portfolio", timeout=15))
        # GetPortfolioV3 nests the fields under a `portfolio` key; _ok strips only the outer `data`.
        # Unwrap it (else budget/positions read empty). Robust to both flat and nested shapes.
        if isinstance(data, dict) and isinstance(data.get("portfolio"), dict):
            data = data["portfolio"]
        if data:
            ctx["budget"] = _accessible_usdc(data)
            for pos in (data.get("positions") or []):
                sym = pos.get("coin") or pos.get("asset")
                if sym:
                    ctx["holdings"].append(sym)
        else:
            ctx["_unavailable"] = True
    except Exception as e:  # noqa
        ctx["_error"] = str(e)
    return ctx


def _pct(mark, prev):
    try:
        m, p = float(mark), float(prev)
        return round((m - p) / p * 100, 2) if p else None
    except (TypeError, ValueError):
        return None


def _candle_trend(candles):
    """Coarse 24h direction from 4h closes: 'up'/'down'/'flat'."""
    try:
        closes = [float(x["c"]) for x in candles if x.get("c")]
        if len(closes) < 4:
            return None
        recent, past = closes[-1], closes[-min(7, len(closes))]  # ~24h on 4h candles
        chg = (recent - past) / past * 100 if past else 0
        return "up" if chg > 1.5 else ("down" if chg < -1.5 else "flat")
    except (TypeError, ValueError, KeyError):
        return None


def _funding_sign(funding):
    try:
        f = float(funding)
    except (TypeError, ValueError):
        return None
    return "positive" if f > 1e-6 else ("negative" if f < -1e-6 else "flat")


def fetch_market_map(client, assets):
    """One batched pass per UNIQUE asset -> a live 'why now' read. Bounded by asset count, not strategy
    count. Built from asset_context (funding, 24h change) + candle trend, enriched with oi_trend +
    market-wide funding_regime when available.
    """
    regime = None
    try:
        regime = (_ok(client.mcp_call("market_get_funding_regime", timeout=8)) or {}).get("regime")
    except Exception:  # noqa
        pass

    uniq = []
    for a in assets:
        if a and a not in uniq:
            uniq.append(a)
    uniq = uniq[:24]   # cap the live fetch; ordered so asset-matched candidates' assets come first

    def one(a):
        kw = dict(asset=a, candle_intervals=["4h"], include_order_book=False,
                  include_funding=False, timeout=12)
        if str(a).startswith("xyz:"):
            kw["dex"] = "xyz"  # HIP-3 assets require the dex param, else INVALID_ARGUMENT
        try:
            data = _ok(client.mcp_call("market_get_asset_data", **kw))
            if not data:
                return (a, {"asset": a})
            ctx = data.get("asset_context") or {}
            oiv = data.get("oi_velocity") or {}
            candles = (data.get("candles") or {}).get("4h") or []
            fact = {
                "asset": a,
                "price_change_24h_pct": _pct(ctx.get("markPx"), ctx.get("prevDayPx")),
                "funding": _funding_sign(ctx.get("funding")),
                "trend": _candle_trend(candles),
                "oi_trend": oiv.get("oi_trend"),        # richer when authenticated
                "funding_regime": regime,               # market-wide; when available
            }
            return (a, {k: v for k, v in fact.items() if v is not None or k == "asset"})
        except Exception:  # noqa
            return (a, {"asset": a})

    try:
        from concurrent.futures import ThreadPoolExecutor
        with ThreadPoolExecutor(max_workers=6) as ex:
            pairs = [p for p in ex.map(one, uniq) if p]   # one(a) -> (a, fact); never raises
    except Exception:  # noqa
        pairs = [one(a) for a in uniq]
    return dict(pairs), regime


# ---------------------------------------------------------------- CLI
def main(argv=None):
    ap = argparse.ArgumentParser(description="senpi strategy discovery engine (concrete filter)")
    # CONCRETE filters only — risk/belief/horizon/scope/goal/experience are the LLM's job (it ranks
    # the returned set on them), so they are deliberately NOT flags here.
    ap.add_argument("--assets")
    ap.add_argument("--direction")
    ap.add_argument("--exclude")
    ap.add_argument("--budget")
    ap.add_argument("--theme", default=None,
                    help="SOFT worldview/market-structure search (e.g. 'k-shape', 'risk-off', "
                         "'market-neutral', 'AI fund'): scores candidates on thesis/tag match + regime "
                         "synonyms and floats matches to the top. Never filters — surfaces + ranks.")
    ap.add_argument("--limit", type=int, default=DEFAULT_LIMIT,
                    help=f"maximum returned candidates (default: {DEFAULT_LIMIT}; explicit values override it)")
    ap.add_argument("--catalog", default=None, help="catalog.json path (default: skill-local → repo → remote fetch)")
    ap.add_argument("--no-market", action="store_true", help="skip the live market enrichment pass")
    ap.add_argument("--context-only", action="store_true",
                    help="return user context only, no match (budget + Senpi holdings + saved-wallet holdings)")
    args = ap.parse_args(argv)

    try:
        records = load_catalog(args.catalog or default_catalog())
    except Exception as e:  # noqa
        print(json.dumps({"candidates": [], "build_custom": {"label": "Build a custom strategy",
              "route": "senpi-strategy-author"}, "meta": {"error": f"catalog load failed: {e}"}}))
        return 1

    by_id = {r.get("id"): r for r in records}

    if args.context_only:
        try:
            uc = fetch_user_context(_get_client(), saved_wallets=True)
        except Exception as e:  # noqa
            uc = {"_error": str(e)}
        print(json.dumps({"user_context": uc}, ensure_ascii=False))
        return 0

    intent = normalize_intent(args)
    # Build the complete eligible set first. Theme scoring must see every survivor; otherwise the default
    # output cap would hide a relevant strategy merely because its neutral alphabetical order was later.
    result = match(intent, records)

    # SOFT theme surface — score/rank the complete survivor set on a worldview keyword (no filtering), then
    # cap the output. Theme-matched candidates' assets therefore get first claim on the live market fetch.
    if args.theme:
        result = apply_theme(result, args.theme)
    result = fold_variants(result, records)   # one card per variant family, ranked by its best member
    result = limit_result(result, args.limit)

    # User's available funds — ALWAYS attach (independent of market enrichment / candidate count) so the
    # LLM can size each pick from real balance, not the per-strategy floor. See SKILL.md Layer 3.
    try:
        result["meta"]["user_context"] = fetch_user_context(_get_client())
    except Exception as e:  # noqa
        result["meta"].setdefault("warnings", []).append(f"user context unavailable: {e}")

    # market enrichment (pass 2): ONE batched fetch over the union of survivors' chosen assets, in
    # candidate order (asset-matched first), capped by unique-asset count inside fetch_market_map.
    if not args.no_market and result["candidates"]:
        user_named = [v for k, v in intent["assets"] if k == "named"]
        per_cand, union = {}, []
        for cand in result["candidates"]:
            assets = by_id.get(cand["id"], {}).get("assets") or []
            pref = [a for a in assets if any(asset_matches(n, [a]) for n in user_named)] or assets
            per_cand[cand["id"]] = pref[:MARKET_FACT_LIMIT]
            for a in pref[:MARKET_FACT_LIMIT]:
                if a not in union:
                    union.append(a)
        try:
            client = _get_client()
            fact_map, _ = fetch_market_map(client, union)
            for cand in result["candidates"]:
                cand["market_facts"] = [fact_map[a] for a in per_cand[cand["id"]] if a in fact_map]
        except Exception as e:  # noqa
            result["meta"].setdefault("warnings", []).append(f"market enrichment unavailable: {e}")

    # Default output must fit OpenClaw's tool-result budget (it truncates past it, breaking the JSON);
    # degrade rather than fail closed. An explicit --limit is an intentional override — no enforcement.
    if args.limit == DEFAULT_LIMIT:
        result = fit_budget(result, OUTPUT_BUDGET)
    print(json.dumps(result, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
